### ISSUE TITLE
[Tracker] Missing Documentation 

### ISSUE THREAD

**Issue by filipworksdev** [goblinengine/goblin#7]
This tracks all the functions missing documentation

## Classes
- [ ] @GDScript eval
- [ ] Node remove_children
- [ ] Array for_each
- [ ] PackedScene instance_add
- [ ] Object new_add (wip)
- [ ] TabContainer  tabs_at_bottom
- [ ] TileSet - multiple functions related to the tile transforms

## Modules
- [ ] VoxelMan - everything
- [ ] ThreadPool - everything
- [ ] SQLite - a number of newer functions
